# Generated by Django 5.1.7 on 2025-06-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImagemCapturada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_imagem', models.TextField(verbose_name='URL da Imagem')),
                ('codigo_lido', models.CharField(max_length=50, verbose_name='Código Identificado')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora da Captura')),
            ],
            options={
                'verbose_name': 'Imagem Capturada',
                'verbose_name_plural': 'Imagens Capturadas',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='LogProcessamentoImagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('sucesso', 'Sucesso'), ('falha', 'Falha'), ('sem_codigo', 'Sem Código Detectado')], max_length=20)),
                ('detalhes', models.TextField(blank=True, null=True)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de Processamento',
                'verbose_name_plural': 'Logs de Processamento',
                'ordering': ['-data_hora'],
            },
        ),
    ]
