# Generated by Django 5.1.7 on 2025-06-02 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imagens', '0001_initial'),
        ('robos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagemcapturada',
            name='robo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagens', to='robos.robo'),
        ),
        migrations.AddField(
            model_name='logprocessamentoimagem',
            name='imagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs_processamento', to='imagens.imagemcapturada'),
        ),
    ]
