# Generated by Django 5.1.7 on 2025-06-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogErro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('origem', models.CharField(max_length=100)),
                ('data_hora', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Log de Erro',
                'verbose_name_plural': 'Logs de Erro',
                'ordering': ['-data_hora'],
            },
        ),
    ]
