# Generated by Django 5.1.7 on 2025-06-02 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs_erro', '0001_initial'),
        ('robos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='logerro',
            name='robo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_erro', to='robos.robo'),
        ),
    ]
