# Generated by Django 5.1.7 on 2025-04-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Armazem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_armazem', models.CharField(max_length=10, unique=True)),
                ('nome', models.CharField(max_length=100)),
                ('qtd_niveis', models.CharField(max_length=10)),
                ('qtd_cidades', models.IntegerField()),
                ('qtd_bairros_por_cidade', models.IntegerField()),
                ('qtd_ruas_por_bairro', models.IntegerField()),
                ('qtd_predios_por_rua', models.IntegerField()),
                ('codigo_barra', models.CharField(blank=True, max_length=50)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Armazéns',
                'ordering': ['nome'],
            },
        ),
    ]
