# Generated by Django 5.1.7 on 2025-06-02 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamentos', '0001_initial'),
        ('armazens', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trajetoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_localizacao', models.CharField(help_text='Formato: cidade:bairro:rua:predio:nivel:apto', max_length=100, verbose_name='Código de Localização')),
                ('data_hora_inicio', models.DateTimeField(verbose_name='Início da Trajetória')),
                ('data_hora_fim', models.DateTimeField(blank=True, null=True, verbose_name='Fim da Trajetória')),
                ('status', models.CharField(choices=[('em_andamento', 'Em Andamento'), ('concluida', 'Concluída'), ('interrompida', 'Interrompida'), ('falha', 'Falha')], default='em_andamento', max_length=20, verbose_name='Status')),
                ('metricas', models.JSONField(default=dict, help_text='Dados de desempenho e sensores', verbose_name='Métricas da Trajetória')),
            ],
            options={
                'verbose_name': 'Trajetória de Inventário',
                'verbose_name_plural': 'Trajetórias de Inventário',
                'ordering': ['agendamento', '-data_hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='EstatisticaInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodo_referencia', models.DateField(verbose_name='Período de Referência')),
                ('data_calculo', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora do Cálculo')),
                ('total_itens', models.PositiveIntegerField(verbose_name='Total de Itens Inventariados')),
                ('itens_por_cidade', models.JSONField(verbose_name='Distribuição por Cidade')),
                ('itens_por_bairro', models.JSONField(verbose_name='Distribuição por Bairro')),
                ('precisao', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Precisão do Inventário (%)')),
                ('tempo_total', models.DurationField(verbose_name='Tempo Total Gasto')),
                ('relatorio', models.FileField(blank=True, null=True, upload_to='relatorios/inventario/', verbose_name='Relatório Completo')),
                ('armazem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estatisticas_inventario', to='armazens.armazem', verbose_name='Armazém relacionado')),
            ],
            options={
                'verbose_name': 'Estatística de Inventário',
                'verbose_name_plural': 'Estatísticas de Inventário',
                'ordering': ['-periodo_referencia'],
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_palete', models.CharField(max_length=50, unique=True, verbose_name='Código Único do Palete')),
                ('codigo_endereco', models.CharField(help_text='Localização física no armazém', max_length=50, verbose_name='Código do Endereço Físico')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data/Hora do Registro')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('verificado', 'Verificado'), ('divergente', 'Divergente'), ('ajustado', 'Ajustado')], default='pendente', max_length=20, verbose_name='Status do Item')),
                ('dados_adicionais', models.JSONField(blank=True, default=dict, verbose_name='Dados Adicionais')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_inventario', to='agendamentos.agendamento', verbose_name='Agendamento relacionado')),
            ],
            options={
                'verbose_name': 'Item de Inventário',
                'verbose_name_plural': 'Itens de Inventário',
                'ordering': ['-data_hora'],
            },
        ),
    ]
