# Generated by Django 5.1.7 on 2025-06-02 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamentos', '0002_initial'),
        ('inventario', '0001_initial'),
        ('robos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='robo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventarios_realizados', to='robos.robo', verbose_name='Robô executor'),
        ),
        migrations.AddField(
            model_name='trajetoria',
            name='agendamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajetorias_inventario', to='agendamentos.agendamento', verbose_name='Agendamento relacionado'),
        ),
        migrations.AddField(
            model_name='trajetoria',
            name='robo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trajetorias_percorridas', to='robos.robo', verbose_name='Robô executor'),
        ),
        migrations.AlterUniqueTogether(
            name='estatisticainventario',
            unique_together={('armazem', 'periodo_referencia')},
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['codigo_palete'], name='inventario__codigo__de3964_idx'),
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['codigo_endereco'], name='inventario__codigo__2b6393_idx'),
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['status'], name='inventario__status_400caf_idx'),
        ),
        migrations.AddIndex(
            model_name='inventario',
            index=models.Index(fields=['agendamento', 'robo'], name='inventario__agendam_643473_idx'),
        ),
        migrations.AddConstraint(
            model_name='inventario',
            constraint=models.UniqueConstraint(fields=('codigo_palete', 'agendamento'), name='unique_palete_por_agendamento'),
        ),
        migrations.AddIndex(
            model_name='trajetoria',
            index=models.Index(fields=['codigo_localizacao'], name='inventario__codigo__dc3a67_idx'),
        ),
        migrations.AddIndex(
            model_name='trajetoria',
            index=models.Index(fields=['status'], name='inventario__status_f88bb9_idx'),
        ),
    ]
