# Generated by Django 5.1.7 on 2025-06-02 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('armazens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacaoAgendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mensagem', models.TextField()),
                ('tipo', models.CharField(choices=[('info', 'Informação'), ('alerta', 'Alerta'), ('erro', 'Erro')], max_length=20)),
                ('lida', models.BooleanField(default=False)),
                ('criada_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificação de Agendamento',
                'verbose_name_plural': 'Notificações de Agendamento',
                'ordering': ['-criada_em'],
            },
        ),
        migrations.CreateModel(
            name='Agendamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('concluido', 'Concluído'), ('aguardando', 'Aguardando'), ('em_andamento', 'Em Andamento'), ('alerta', 'Alerta'), ('problema', 'Problema'), ('cancelado', 'Cancelado')], default='aguardando', max_length=20)),
                ('tipo', models.CharField(choices=[('completo', 'Inventário Completo'), ('parcial', 'Inventário Parcial'), ('emergencial', 'Verificação Emergencial')], default='completo', max_length=20)),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField()),
                ('descricao', models.TextField(blank=True, null=True)),
                ('cidades', models.JSONField(blank=True, default=list)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('excluido_em', models.DateTimeField(blank=True, null=True)),
                ('armazem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agendamentos', to='armazens.armazem')),
                ('excluido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agendamentos_excluidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agendamento',
                'verbose_name_plural': 'Agendamentos',
                'ordering': ['-data_inicio'],
            },
        ),
    ]
