# Generated by Django 5.1.7 on 2025-03-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('matricula', models.CharField(max_length=20, unique=True)),
                ('departamento', models.CharField(blank=True, max_length=50)),
                ('cargo', models.CharField(blank=True, max_length=50)),
                ('tipo', models.CharField(choices=[('Master', 'Master'), ('Admin', 'Admin'), ('Usuario', 'Usuario')], default='Usuario', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
