# Generated by Django 5.1.7 on 2025-03-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nome',
            field=models.CharField(default='Usuário Padrão', max_length=255),
        ),
    ]
