# Generated by Django 5.1.7 on 2025-03-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('usuarios', '0004_usuario_groups_usuario_is_active_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usuario',
            constraint=models.UniqueConstraint(condition=models.Q(models.Q(('matricula', None), _negated=True), models.Q(('matricula', ''), _negated=True)), fields=('matricula',), name='unique_matricula'),
        ),
    ]
