# Generated by Django 5.1.7 on 2025-06-02 14:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('armazens', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Robo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificador', models.CharField(max_length=50, unique=True)),
                ('modelo', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo'), ('em_missao', 'Em Missão'), ('manutencao', 'Em Manutenção'), ('erro', 'Erro')], default='inativo', max_length=20)),
                ('habilitado', models.BooleanField(default=True)),
                ('sensores', models.JSONField(default=dict)),
                ('ultima_comunicacao', models.DateTimeField(auto_now=True)),
                ('configuracao', models.JSONField(default=dict)),
                ('armazem', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='robos', to='armazens.armazem')),
            ],
            options={
                'verbose_name': 'Robô',
                'verbose_name_plural': 'Robôs',
                'ordering': ['identificador'],
            },
        ),
        migrations.CreateModel(
            name='ComandoRobo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('desligar', 'Desligar'), ('reiniciar', 'Reiniciar'), ('pausar', 'Pausar Missão'), ('retomar', 'Retomar Missão'), ('emergencia', 'Parada de Emergência')], max_length=20)),
                ('executado', models.BooleanField(default=False)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_execucao', models.DateTimeField(blank=True, null=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('robo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandos', to='robos.robo')),
            ],
            options={
                'verbose_name': 'Comando para Robô',
                'verbose_name_plural': 'Comandos para Robôs',
                'ordering': ['-data_criacao'],
            },
        ),
    ]
