# Generated by Django 5.1.7 on 2025-06-02 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('agendamentos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trajetoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_localizacao', models.CharField(help_text='Formato: cidade:bairro:rua:predio:nivel:apto', max_length=100, verbose_name='Código de Localização')),
                ('data_hora', models.DateTimeField(auto_now_add=True, verbose_name='Data e Hora')),
                ('dados_sensores', models.JSONField(default=dict, help_text='Dados coletados durante a trajetória', verbose_name='Dados dos Sensores')),
                ('agendamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajetorias_principal', related_query_name='trajetoria_principal', to='agendamentos.agendamento', verbose_name='Agendamento relacionado')),
            ],
            options={
                'verbose_name': 'Trajetória',
                'verbose_name_plural': 'Trajetórias',
                'ordering': ['-data_hora'],
            },
        ),
        migrations.CreateModel(
            name='PontoInteresse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código RFID ou QR Code', max_length=50, verbose_name='Código')),
                ('tipo', models.CharField(choices=[('inicio', 'Ponto de Início'), ('fim', 'Ponto de Fim'), ('checkpoint', 'Checkpoint'), ('obstaculo', 'Obstáculo Detectado')], max_length=20, verbose_name='Tipo de Ponto')),
                ('dados', models.JSONField(default=dict, verbose_name='Dados Adicionais')),
                ('data_hora', models.DateTimeField(verbose_name='Data e Hora')),
                ('trajetoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pontos_interesse', to='trajetorias.trajetoria', verbose_name='Trajetória associada')),
            ],
            options={
                'verbose_name': 'Ponto de Interesse',
                'verbose_name_plural': 'Pontos de Interesse',
            },
        ),
        migrations.AddIndex(
            model_name='trajetoria',
            index=models.Index(fields=['codigo_localizacao'], name='trajetorias_codigo__c7970b_idx'),
        ),
    ]
